language: elixir

elixir:
  - 1.3
  - 1.4

otp_release:
  - 18
  - 19
  - 20

script:
  - yes | mix deps.get
  - MIX_ENV=test mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
