language: elixir

elixir:
  - 1.4

otp_release:
  - 18.3
  - 19.3
  - 20.0

# matrix:
#   exclude:
#     - elixir: 1.3
#       otp_release: 20.0

script:
  - yes | mix deps.get
  - MIX_ENV=test mix test

after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
